### ISSUE TITLE
3 minor UI/administrative issues appear on 'Treasury' page ( https://genesis.eden.eoscommunity.org/treasury )

### ISSUE THREAD

**Issue by earthman01** [gofractally/Eden#611]
3 minor UI/administrative issues appear on the 'Treasury' page ( https://genesis.eden.eoscommunity.org/treasury ) as follows:

1) 'Per 1 Delegate' should read 'Per Level 1 Delegate'
2) 'Per Head-chief Delegate' should read 'Per Head Chief Delegate'
3) The Head Chief Delegate amount is misaligned on my Mac/Safari browser. (See screenshot)

![D37EF537-D21F-4D08-B4B7-132765EF3FE0_1_201_a](https://user-images.githubusercontent.com/4332714/142279202-b589816b-4335-41fd-929c-d3b54b239fe0.jpeg)

**Comment by brandonfancher** [comment]
These issues were addressed in the aforementioned PR.
