### ISSUE TITLE
tester: use eosio/authority rather than tester equivalent

### ISSUE THREAD

**Issue by James-Mart** [gofractally/Eden#664]
```struct tester_permission_level_weight```, ```struct tester_wait_weight```, and ```struct tester_authority``` are in tester.cpp, and therefore not visible to tester users.

These structs should be externally accessible, to make it easier for users to call actions in test-cases to update account permissions, etc.

**Comment by James-Mart** [comment]
What was the reason for not simply putting them in the eosio namespace in the header?

**Comment by tbfleming** [comment]
They were temporary until the eosio namespace got versions of those. They can be removed now. See `eosio/authority.hpp`.
